# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:

- task: InstallAppleCertificate@2
  inputs:
    certSecureFile: 'ionicblank-certificates.p12'
    certPwd: "$(CERT_PASSWORD)"
    keychain: 'temp'
    keychainPassword: "$(KEY_CHAIN_PASSWORD)"

- task: InstallAppleProvisioningProfile@1
  inputs:
    provisioningProfileLocation: 'secureFiles'
    provProfileSecureFile: 'ionicblank.mobileprovision'

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: "$(APP_SCHEME)"
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 8, 9, 10, 11, 12, default, specifyPath

- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    pip install --upgrade pip
    pip install fastlane
  displayName: 'Install Fastlane'

- script: |
    mkdir -p fastlane
    echo 'json_key_content("$(APP_STORE_CONNECT_API_KEY_JSON)")' > fastlane/Appfile
    echo 'default_platform(:ios)
          lane :upload do
            build_app(scheme: "$(APP_SCHEME)", export_method: "app-store", output_directory: "./output")
            upload_to_testflight
          end' > fastlane/Fastfile
  displayName: 'Configure Fastlane'

- script: |
    fastlane upload
  displayName: 'Upload to TestFlight'